server:
  port: 8080
  tomcat:
    threads:
      max: 50
      min-spare: 10
    connection-timeout: 1500

spring:
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: password
  jpa:
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true
          show_sql: true
management:
  endpoints.web.exposure.include: '*'
  tracing:
    enabled: true
    sampling.probability: 1.0
    propagation:
      type: b3
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE
      hibernate:
        orm:
        jdbc:
          bind: TRACE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
